// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package database

import (
	"context"
	"database/sql"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (created_at, updated_at, slug, name, agent_id)
VALUES (
        NOW(),
        NOW(),
        $1,
        $2,
        $3
       )
RETURNING id, created_at, updated_at, slug, name, agent_id, visit_count, has_called
`

type CreateUserParams struct {
	Slug    string
	Name    string
	AgentID sql.NullString
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Slug, arg.Name, arg.AgentID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Slug,
		&i.Name,
		&i.AgentID,
		&i.VisitCount,
		&i.HasCalled,
	)
	return i, err
}

const getVisitorBySlug = `-- name: GetVisitorBySlug :one
SELECT id, created_at, updated_at, slug, name, agent_id, visit_count, has_called FROM users WHERE slug = $1
`

func (q *Queries) GetVisitorBySlug(ctx context.Context, slug string) (User, error) {
	row := q.db.QueryRowContext(ctx, getVisitorBySlug, slug)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Slug,
		&i.Name,
		&i.AgentID,
		&i.VisitCount,
		&i.HasCalled,
	)
	return i, err
}

const incrementVisit = `-- name: IncrementVisit :one
UPDATE users SET visit_count = visit_count + 1 WHERE slug = $1 RETURNING id, created_at, updated_at, slug, name, agent_id, visit_count, has_called
`

func (q *Queries) IncrementVisit(ctx context.Context, slug string) (User, error) {
	row := q.db.QueryRowContext(ctx, incrementVisit, slug)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Slug,
		&i.Name,
		&i.AgentID,
		&i.VisitCount,
		&i.HasCalled,
	)
	return i, err
}

const setHasCalled = `-- name: SetHasCalled :one
UPDATE users SET has_called = TRUE WHERE slug = $1 RETURNING id, created_at, updated_at, slug, name, agent_id, visit_count, has_called
`

func (q *Queries) SetHasCalled(ctx context.Context, slug string) (User, error) {
	row := q.db.QueryRowContext(ctx, setHasCalled, slug)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Slug,
		&i.Name,
		&i.AgentID,
		&i.VisitCount,
		&i.HasCalled,
	)
	return i, err
}
